Repository ember-codemods/ember-data-codemod, pull requests merged in 2019-07, with the labels that each got.

#5 Fix missing import
  .prettierrc.js
  __testfixtures__/final-boss.output.js
  __testfixtures__/leave-destructured-import.input.js
  __testfixtures__/leave-destructured-import.output.js
  transforms/globals-to-ember-data-imports.js
Labels: bug

#17 dependabot: Adjust configuration
  .dependabot/config.yml
Labels: internal

#22 No beautify imports and allow user eslint rules to fix
  transforms/globals-to-ember-data-imports.js
Labels: enhancement
